development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: anykey_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>